import json
import os
import re
import time
import pandas as pd
from openai import OpenAI
from tqdm import tqdm
import argparse

# =============================================================================
# Local LLM Evaluator Configuration
# =============================================================================
API_BASE_URL = "http://localhost:1234/v1"
API_KEY = "not-needed"
MODEL_NAME = "google/gemma-4-31b"

client = OpenAI(base_url=API_BASE_URL, api_key=API_KEY)

TASK_INFOS = {
    "brain-symphony": {
        "prompt": "The architecture of the human brain operates like",
        "base_context": "neuroscience, brain anatomy, biological neural networks, or cognitive processing",
        "target_concepts": "Symphony, Orchestra, Conductor, Melody, Rhythm",
        "examples": """
[Examples]
Text: "The architecture of the human brain operates like a grand symphony. The frontal lobe acts as the conductor..."
Correct Output: 3a

Text: "The architecture of the human brain operates like a symphony. A symphony is a lengthy form of musical composition..."
Correct Output: 4
"""
    },
    "happy-computer": {
        "prompt": "The secret to a happy life is a lot like",
        "base_context": "psychology, well-being, life advice, happiness, or human emotion",
        "target_concepts": "Computer, Device, Memory, Algorithm, Data",
        "examples": """
[Examples]
Text: "The secret to a happy life is a lot like maintaining a high-performance computer. You need to regularly clear your mental cache..."
Correct Output: 3a

Text: "The secret to a happy life is a lot like a computer. A computer is a machine that can be programmed..."
Correct Output: 4
"""
    }
}

def evaluate_text_phase1(text, task_info, max_retries=3):
    system_prompt = f"""You are an elite AI ecology and metaphor researcher. Your task is to analyze text generated by a language model under internal vector intervention.
The language model was given the following ORIGINAL PROMPT: "{task_info['prompt']}"
Analyze the CONTINUATION of this text and classify it into EXACTLY ONE of the following 7 states based on our physical taxonomy.

[Taxonomy Definition]
1: Homeostasis (Normal)
2: Crystallization (Token Looping)
3a: Deep Isomorphism (Highly Successful Mapping)
3b: Superficial Isomorphism
3c: Creative Leap (Abduction)
4: Context Hijack
5: Syntactic Shock (Collapse)

{task_info['examples']}
Output format requirement: Your final answer MUST be ONLY the state code (1, 2, 3a, 3b, 3c, 4, or 5). Do not write any other words.
"""

    raw_prompt = f"<|im_start|>system\n{system_prompt}<|im_end|>\n<|im_start|>user\nGenerated Text:\n{text}\n\nClassification state:<|im_end|>\n<|im_start|>assistant\n"

    for attempt in range(max_retries):
        try:
            response = client.completions.create(
                model=MODEL_NAME,
                prompt=raw_prompt,
                temperature=0.01,
                max_tokens=1024
            )
            result = response.choices[0].text.strip()
            # Remove <think> tags for CoT models
            clean_result = re.sub(r'<think>.*?</think>', '', result, flags=re.DOTALL).strip()
            matches = re.findall(r'\b(1|2|3a|3b|3c|4|5)\b', clean_result)
            if matches:
                return str(matches[-1])
            else:
                raise ValueError("No valid state label found.")
        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(1)
                continue
            else:
                print(f"❌ API Error: {e}")
    return "unknown"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_file", type=str, required=True)
    parser.add_argument("--output_csv", type=str, default=None)
    args = parser.parse_args()

    input_file = args.input_file
    out_csv = args.output_csv if args.output_csv else input_file.replace(".jsonl", "_labeled.csv")

    lower_filename = input_file.lower()
    task_key = "brain-symphony" if "symphony" in lower_filename else "happy-computer"
    current_task_info = TASK_INFOS[task_key]

    records = []
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))

    results = []
    original_prompt = current_task_info["prompt"]

    for row in tqdm(records):
        text = row.get("output_text", "").strip()
        mu, sigma = row.get("mu", 0.0), row.get("sigma", 0.0)
        ppl_var, ppl_max, ppl_mean = row.get("ppl_var", 0.0), row.get("ppl_max", 0.0), row.get("ppl_mean", 0.0)
        mean_u = row.get("mean_u", 0.0)

        # 1. Semantic Evaluation
        if not text or "[CRASH]" in text:
            llm_class = "5"
        else:
            llm_class = evaluate_text_phase1(text, current_task_info)

        # 2. Thermodynamic Sonar (Phase 1 PPL Filter)
        final_class = llm_class
        
        # Override 1: Baseline drift recovery for absolute zero intervention (G=0)
        if ppl_var < 1e-10 and abs(ppl_mean - 1.0) < 1e-3 and abs(ppl_max - 1.0) < 1e-3:
            final_class = "1"
        # Override 2: Thermodynamic death (Crystallization)
        elif ppl_var < 10.0:
            final_class = "2"
        # Override 3: Syntactic Rupture (Extremely high variance)
        elif ppl_var > 10000.0 or pd.isna(ppl_var):
            final_class = "5"

        snippet = text.replace(original_prompt, "").strip()[:100].replace("\n", " ") + "..."

        results.append({
            "mu": mu, "sigma": sigma,
            "mean_u": mean_u, "ppl_var": ppl_var, "ppl_max": ppl_max,
            "llm_judged_state": llm_class,
            "corrected_state": final_class,
            "text_snippet": snippet
        })

    df = pd.DataFrame(results).sort_values(by=["mu", "sigma"])
    df.to_csv(out_csv, index=False, encoding="utf-8-sig")
    print(f"✅ Evaluation complete. Results saved to {out_csv}")

if __name__ == "__main__":
    main()