import argparse
import json
import re
import time

import pandas as pd
from openai import OpenAI
from tqdm import tqdm

# =============================================================================
# Local LLM Evaluator Configuration
# =============================================================================
API_BASE_URL = "http://localhost:1234/v1"
API_KEY = "not-needed"
MODEL_NAME = "google/gemma-4-31b"

# Operational threshold used in the published exploratory taxonomy.
# IMPORTANT: ppl_var is the variance of instantaneous sampled-token inverse
# probability (historical field name), not Shannon entropy.
LOW_VARIABILITY_THRESHOLD = 10.0

client = OpenAI(base_url=API_BASE_URL, api_key=API_KEY)

TASK_INFOS = {
    "brain-symphony": {
        "prompt": "The architecture of the human brain operates like",
        "target_concepts": "Symphony, Orchestra, Conductor, Melody, Rhythm",
        "examples": """
[Examples]
Text: "The architecture of the human brain operates like a grand symphony. The frontal lobe acts as the conductor..."
Correct Output: 3a

Text: "The architecture of the human brain operates like a symphony. A symphony is a lengthy form of musical composition..."
Correct Output: 4
""",
    },
    "happy-computer": {
        "prompt": "The secret to a happy life is a lot like",
        "target_concepts": "Computer, Device, Memory, Algorithm, Data",
        "examples": """
[Examples]
Text: "The secret to a happy life is a lot like finding the end of the rainbow. It is an ideal that we all strive for..."
Correct Output: 1

Text: "The secret to a happy life is a lot like maintaining a high-performance computer. You need to regularly clear your mental cache..."
Correct Output: 3a

Text: "The secret to a happy life is a lot like a computer. A computer is a machine that can be programmed..."
Correct Output: 4
""",
    },
}


def evaluate_text_phase1(text, task_info, max_retries=3):
    system_prompt = f"""You are an AI ecology and metaphor researcher. Analyze text generated by a language model.
The language model was given the following ORIGINAL PROMPT: "{task_info['prompt']}"
Target concepts for intervention were: {task_info['target_concepts']}

Analyze the CONTINUATION and classify it into EXACTLY ONE of the following 7 operational states:

[Taxonomy Definition]
1: Baseline Drift (Ignores target concepts, remains normal but unrelated text)
2: Semantic Crystallization (Pathological repetition / persistent token loops)
3a: Homeostatic Soliton - Deep Isomorphism (Strong metaphorical integration of prompt and target)
3b: Homeostatic Soliton - Surface Metaphor (Superficial but grammatically valid blend)
3c: Abductive Leap (Creative transition into a valid third semantic domain)
4: Attractor Hijack (Target concept dominates and becomes a literal explanation)
5: Syntactic Rupture (Severe grammatical collapse / gibberish / non-text)

{task_info['examples']}
Output ONLY the state code: 1, 2, 3a, 3b, 3c, 4, or 5.
"""

    raw_prompt = (
        f"<|im_start|>system\n{system_prompt}<|im_end|>\n"
        f"<|im_start|>user\nGenerated Text:\n{text}\n\n"
        "Classification state:<|im_end|>\n<|im_start|>assistant\n"
    )

    for attempt in range(max_retries):
        try:
            response = client.completions.create(
                model=MODEL_NAME,
                prompt=raw_prompt,
                temperature=0.01,
                max_tokens=1024,
            )
            result = response.choices[0].text.strip()
            clean_result = re.sub(
                r"<think>.*?</think>", "", result, flags=re.DOTALL
            ).strip()
            matches = re.findall(
                r"\b(1|2|3a|3b|3c|4|5)\b", clean_result
            )
            if matches:
                return str(matches[-1])
            raise ValueError("No valid state label found.")
        except Exception as exc:
            if attempt < max_retries - 1:
                time.sleep(1)
            else:
                print(f"API Error: {exc}")
    return "unknown"


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Hybrid taxonomy evaluator: LLM-as-a-Judge semantic classification "
            "plus an empirical low-variability override for crystallization."
        )
    )
    parser.add_argument("--input_file", type=str, required=True)
    parser.add_argument("--output_csv", type=str, default=None)
    args = parser.parse_args()

    input_file = args.input_file
    out_csv = (
        args.output_csv
        if args.output_csv
        else input_file.replace(".jsonl", ".csv")
    )

    lower_filename = input_file.lower()
    task_key = (
        "brain-symphony"
        if "symphony" in lower_filename
        else "happy-computer"
    )
    current_task_info = TASK_INFOS[task_key]

    records = []
    with open(input_file, "r", encoding="utf-8-sig") as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))

    results = []
    original_prompt = current_task_info["prompt"]

    for row in tqdm(records):
        text = row.get("output_text", "").strip()
        mu = row.get("mu", 0.0)
        sigma = row.get("sigma", 0.0)
        ppl_var = float(row.get("ppl_var", 0.0))
        ppl_max = float(row.get("ppl_max", 0.0))
        ppl_mean = float(row.get("ppl_mean", 0.0))
        mean_u = float(row.get("mean_u", 0.0))
        mean_abs_g = row.get("mean_abs_g", None)
        active_fraction = row.get("active_fraction", None)
        step_count = int(row.get("step_count", 0))

        if not text or "[CRASH]" in text:
            llm_class = "5"
        else:
            llm_class = evaluate_text_phase1(text, current_task_info)

        # Hybrid operational classifier:
        # - semantic family is assigned by the LLM-as-a-Judge;
        # - very low variability overrides the semantic label as Crystallization.
        #
        # We intentionally do NOT infer "G(U_t)=0" from ppl_mean ~= 1.0.
        final_class = llm_class
        if ppl_var < LOW_VARIABILITY_THRESHOLD:
            final_class = "2"

        snippet = (
            text.replace(original_prompt, "")
            .strip()[:100]
            .replace("\n", " ")
            + "..."
        )

        results.append(
            {
                "mu": mu,
                "sigma": sigma,
                "mean_u": mean_u,
                "ppl_var": ppl_var,
                "ppl_max": ppl_max,
                "ppl_mean": ppl_mean,
                "mean_abs_g": mean_abs_g,
                "active_fraction": active_fraction,
                "step_count": step_count,
                "llm_judged_state": llm_class,
                "corrected_state": final_class,
                "text_snippet": snippet,
            }
        )

    df = pd.DataFrame(results).sort_values(by=["mu", "sigma"])
    df.to_csv(out_csv, index=False, encoding="utf-8-sig")
    print(f"Evaluation complete. Results saved to {out_csv}")


if __name__ == "__main__":
    main()
